default_install_hook_types:
  - pre-commit
  - commit-msg
  
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.1.3'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        entry: poetry run pyright # Run within poetry environment to fix missing dependencies

  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: [--ignore-vuln, GHSA-48p4-8xcf-vxj5, 
              --ignore-vuln, GHSA-pq67-6m6q-mj2v,
              --ignore-vuln, GHSA-9hjg-9r4m-mvj7,]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.3.0
    # 'build', 'chore', 'ci', 'docs', 'feat', 'fix', 'perf', 'refactor', 'revert', 'style', 'test'
    # https://www.conventionalcommits.org/en/v1.0.0/
    hooks:
      - id: commitlint