services:
  dev:
    build:
      context: .
      target: development
    # volumes + command here to copy the src folder and edit it in the container without
    # modifying the local src folder
    volumes:
      - .:/cache:ro
    command: bash -c "cp -r /cache/src /app/src && poetry install --only-root && tail -f /dev/null"
    tty: true
    stdin_open: true

  test:
    build:
      context: .
      target: test
    volumes:
      - ./tests:/app/tests:ro


  prod:
    build:
      context: .
      target: production
