services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "10000:10000"
    env_file:
      - .env.backend
    command: backend.app.main:app --host 0.0.0.0 --port 10000
    volumes:
      - ./cardwise:/app/cardwise
      - ./backend:/app/backend
    networks:
      - cardwise-net

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    env_file:
      - .env.cli
    environment:
      - BACKEND_API_URL=http://backend:10000
    stdin_open: true      # Allow interactive mode
    tty: true
    volumes:
      - ./cli:/app/cli
      - ./cardwise:/app/cardwise
      - ./ingestion:/app/ingestion
    networks:
      - cardwise-net
    entrypoint: /bin/bash

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile.ingestion
    env_file:
      - .env.ingestion
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ./cardwise:/app/cardwise
      - ./ingestion:/app/ingestion

networks:
  cardwise-net:
    driver: bridge
