name: setup-python-poetry
description: Setup python with Poetry, making sure to cache the dependencies using poetry.lock as a hash
inputs:
  python-version:
    description: Python version to use

runs:
  using: composite
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: snok/install-poetry@v1

      - name: Set up Python and cache poetry
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'

      - run: |
          poetry env use ${{ inputs.python-version }}
          poetry install
        shell: bash