name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"  # Caches Poetry dependencies

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root  # Faster install, no unnecessary build

      - name: Run Tests
        run: poetry run pytest --cov=src --cov-report=term-missing

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aydin-ab/cardwise

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruff (if missing)
        run: pip install ruff  # ✅ Install only Ruff, no need for full Poetry setup

      - name: Run Ruff (Lint & Format Check)
        run: ruff check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pyright (if missing)
        run: pip install pyright  # ✅ Install only Pyright, no need for full Poetry setup

      - name: Run Pyright
        run: pyright
