name: CI  # Continuous Integration Workflow

on:
  push:
    branches: [main, dev]  # Run Pyright on pushes to main and dev branches
  pull_request:
    branches: [main, dev]  # Run on PRs targeting main and dev

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch your repo code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Matches your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # Install dev dependencies

      - name: Run Ruff (Lint & Format Check)
        run: ruff check .

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2

      - name: Run Tests
        run: pytest --cov=src --cov-report=term-missing

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aydin-ab/cardwise

