name: CI  # Continuous Integration Workflow

on:
  push:  # Run on every push
    branches: [main, dev]  # Change to your branch names
  pull_request:  # Run on PRs to ensure quality before merging

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch your repo code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Matches your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # Install dev dependencies

      - name: Run Ruff (Lint & Format Check)
        run: ruff check .

      - name: Run Tests
        run: pytest --cov=src --cov-report=term-missing

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3  # Upload test coverage report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Add this in your GitHub secrets
          files: coverage.xml
          fail_ci_if_error: true  # Fails CI if Codecov fails
