name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  pytest:
    name: Pytest & Codecov (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: aydin-ab/setup-python-poetry-action@v1.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: poetry run pytest --cov=src --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aydin-ab/cardwise

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruff
        uses: astral-sh/ruff-action@v3
      - name: Run ruff
        run: |
          ruff check --fix
          ruff format

  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup python and poetry
        uses: aydin-ab/setup-python-poetry-action@v1.1.0

      - name: Add poetry bin to PATH (to use the pyright action)
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release


  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup python and poetry
        uses: aydin-ab/setup-python-poetry-action@v1.1.0

      - run: poetry export --without-hashes --output requirements.txt

      - name: 'Run pip-audit'
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
