name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  pytest:
    name: Pytest & Codecov (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install  # Faster install, no unnecessary build

      - name: Run Tests
        run: poetry run pytest --cov=src --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aydin-ab/cardwise

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruff (if missing)
        run: pip install ruff  # ✅ Install only Ruff, no need for full Poetry setup

      - name: Run Ruff (Lint & Bandit)
        run: ruff check .

      - name: Run Ruff (Format)
        run: ruff format

  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pyright (if missing)
        run: pip install pyright  # ✅ Install only Pyright, no need for full Poetry setup

      - name: Run Pyright
        run: pyright

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit
        run: pip-audit
