name: Monthly Ingestion

on:
  schedule:
    - cron: '0 8 1 * *'  # At 08:00 on the 1st of every month (UTC)
  workflow_dispatch:

jobs:
  run-ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python and poetry
        uses: aydin-ab/setup-python-poetry-action@v1.1.0

      - name: Run ingestion
        env:
          GCS_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          LOG_LEVEL: INFO
        run: poetry run python ingestion/main.py
      