name: Monthly Ingestion

on:
  schedule:
    - cron: '01 7 1 * *'  # At 07:01 UTC on the 1st of every month (= 00:01 PT)
  workflow_dispatch:

jobs:
  run-ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python and poetry
        uses: aydin-ab/setup-python-poetry-action@v1.1.0

      - name: Run ingestion
        env:
          GCS_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          LOG_LEVEL: INFO
        run: poetry run python -c "from ingestion.main import main; main(upload=True)"
      