name: Keep Backend Warm

on:
  schedule:
    - cron: '*/12 15-23,0-6 * * *'  # Every 12 minutes from 15:00 to 7:59 next day UTC (= 8:00 to 23:59 PT) 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://cardwise-backend-latest.onrender.com/ping
