name: Keep Backend Warm

on:
  schedule:
    - cron: '*/1 15-23 * * *'  # Every 12 minutes from 15:00 to 7:59 next day UTC (= 8:00 to 23:59 PT) 
    - cron: '*/1 0-6 * * *'    # 12AM–8AM PT (00:00–07:59 UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://cardwise-backend-latest.onrender.com/ping
