version: 1
disable_existing_loggers: False

formatters:
  file_formatter:
    format: "%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d in %(funcName)s — %(message)s"
  colored_formatter:
    format: "%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d in %(funcName)s — %(message)s"
    class: coloredlogs.ColoredFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored_formatter
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: file_formatter
    filename: "backend/logs/backend.log"
    maxBytes: 5000000  # 5 MB
    backupCount: 3

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: file_formatter
    filename: "backend/logs/errors.log"
    maxBytes: 2000000  # 2 MB
    backupCount: 2

loggers:
  backend:
    level: INFO
    handlers: [console, file, error_file]
    propagate: False
